version: '3.1'

services:

  # envipath services
  envipath:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/kurtw555/cts-envipath:dev-kube
    # image: cts-envipath
    container_name: cts-envipath
    ports:
      - "5003:5003"
    environment:
      - HOSTNAME=docker
    env_file:
      - ./.env
