
services:
  envipath:
    restart: unless-stopped
    image: ghcr.io/quanted/cts-envipath:dev-2befb4fe0bacb427cdbcf171d577bb17cccee44f
    container_name: cts-envipath
    ports:
      - "5003:5003"
    environment:
      - HOSTNAME=docker
    env_file:
      - ./.env
