version: '3.1'

services:

  # envipath services
  envipath:
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: quanted/cts-envipath
    container_name: envipath
    ports:
      - "5003:5003"
    environment:
      - HOSTNAME=docker
    volumes:
      - ../:/src/
    env_file:
      - ./.env
